# Generated by Django 6.0.2 on 2026-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('ready', 'Ready for Shipping'), ('out', 'Out For Delivery')], default='received', max_length=20),
        ),
    ]
